apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  labels:
    app: app01
spec:
  selector:
    matchLabels:
      app: app01
  replicas: 2
  template:
    metadata:
      annotations:
      labels:
        app: app01
    spec:
      containers:
      - name: app01
        image: devopsabi/demo-app-k8s:01
        ports:
        - containerPort: 8080
        envFrom:
            - configMapRef:
                name: demo-app-cm # Kustomize will automatically update this name
      volumeMounts:
        - name: config-volume
          mountPath: /app-test/application.properties
          subPath: application.properties # Mounts just the file, not the folder
      volumes:
      - name: config-volume
        configMap:
          name: app-properties # Kustomize handles the name hashing automatically
